// AUTO-GENERATED property inventory for the HomeFind realtor app.
// Every listing references a distinct cover image in /public/assets/realtor —
// no image or property is used twice. Cover art (gen-*.jpg) was produced with
// Higgsfield across 25 distinct architectural archetypes for maximum diversity.
// To regenerate, see scripts/realtor (prompts + archetype metadata).

export type Listing = {
  id: string;
  cover: string;
  status: 'sale' | 'rent';
  price: number;
  beds: number;
  baths: number;
  sqft: number;
  year: number;
  building: string;
  address: string;
  city: string;
  type: string;
  agent: string;
  desc: string;
  features: string[];
};

export const AGENTS: Record<string, string> = {
  'Dana Whitmore': 'Senior Listing Agent',
  'Marcus Reed': 'Residential Specialist',
  'Priya Anand': 'Luxury Portfolio Advisor',
  'Elena Cruz': 'Broker Associate',
};

export const LISTINGS: Listing[] = [
  { id: 'g-midcentury-1', cover: 'gen-midcentury-1', status: 'rent', price: 3800, beds: 2, baths: 2, sqft: 1600, year: 1958, building: 'The Alexander', address: '100 Sunmor Dr', city: 'Palm Springs, CA', type: 'Mid-Century Modern Rental', agent: 'Dana Whitmore', desc: 'A restored mid-century modern with walls of glass, clerestory windows and a butterfly roofline. Terrazzo floors and a walled pool courtyard keep the desert-modern spirit intact.', features: ['Restored terrazzo floors', 'Clerestory windows', 'Walled pool courtyard', 'Butterfly roofline', 'Original block screens', 'Mountain views'] },
  { id: 'g-midcentury-2', cover: 'gen-midcentury-2', status: 'sale', price: 1070000, beds: 3, baths: 2, sqft: 2030, year: 1963, building: 'Sunmor Modern', address: '311 Twin Palms Rd', city: 'Tucson, AZ', type: 'Mid-Century Modern', agent: 'Marcus Reed', desc: 'A restored mid-century modern with walls of glass, clerestory windows and a butterfly roofline. Terrazzo floors and a walled pool courtyard keep the desert-modern spirit intact.', features: ['Restored terrazzo floors', 'Clerestory windows', 'Walled pool courtyard', 'Butterfly roofline', 'Original block screens', 'Mountain views'] },
  { id: 'g-midcentury-3', cover: 'gen-midcentury-3', status: 'sale', price: 1360000, beds: 3, baths: 2, sqft: 2470, year: 1967, building: 'Twin Palms House', address: '522 Canyon View Ln', city: 'Las Vegas, NV', type: 'Mid-Century Modern', agent: 'Priya Anand', desc: 'A restored mid-century modern with walls of glass, clerestory windows and a butterfly roofline. Terrazzo floors and a walled pool courtyard keep the desert-modern spirit intact.', features: ['Restored terrazzo floors', 'Clerestory windows', 'Walled pool courtyard', 'Butterfly roofline', 'Original block screens', 'Mountain views'] },
  { id: 'g-midcentury-4', cover: 'gen-midcentury-4', status: 'sale', price: 1650000, beds: 4, baths: 3, sqft: 2900, year: 1972, building: 'Atomic Ranch', address: '733 Desert Star Way', city: 'Joshua Tree, CA', type: 'Mid-Century Modern', agent: 'Elena Cruz', desc: 'A restored mid-century modern with walls of glass, clerestory windows and a butterfly roofline. Terrazzo floors and a walled pool courtyard keep the desert-modern spirit intact.', features: ['Restored terrazzo floors', 'Clerestory windows', 'Walled pool courtyard', 'Butterfly roofline', 'Original block screens', 'Mountain views'] },
  { id: 'g-paintedlady-1', cover: 'gen-paintedlady-1', status: 'sale', price: 1150000, beds: 3, baths: 2, sqft: 2200, year: 1885, building: 'The Painted Lady', address: '137 Steiner St', city: 'San Francisco, CA', type: 'Victorian', agent: 'Elena Cruz', desc: 'An impeccably kept Victorian painted lady with ornate gingerbread trim, soaring bay windows and a striking multi-color facade. Period detail meets fully updated systems inside.', features: ['Ornate period millwork', 'Double-parlor layout', 'Updated chef\'s kitchen', 'Bay windows', 'Landmark district', 'Garden level suite'] },
  { id: 'g-paintedlady-2', cover: 'gen-paintedlady-2', status: 'rent', price: 6650, beds: 4, baths: 3, sqft: 2730, year: 1892, building: 'Rosemont Victorian', address: '348 Fulton Ave', city: 'Alameda, CA', type: 'Victorian Rental', agent: 'Dana Whitmore', desc: 'An impeccably kept Victorian painted lady with ornate gingerbread trim, soaring bay windows and a striking multi-color facade. Period detail meets fully updated systems inside.', features: ['Ornate period millwork', 'Double-parlor layout', 'Updated chef\'s kitchen', 'Bay windows', 'Landmark district', 'Garden level suite'] },
  { id: 'g-paintedlady-3', cover: 'gen-paintedlady-3', status: 'sale', price: 2515000, beds: 4, baths: 3, sqft: 3270, year: 1898, building: 'Gingerbread House', address: '559 Gaslight Row', city: 'Cape May, NJ', type: 'Victorian', agent: 'Marcus Reed', desc: 'An impeccably kept Victorian painted lady with ornate gingerbread trim, soaring bay windows and a striking multi-color facade. Period detail meets fully updated systems inside.', features: ['Ornate period millwork', 'Double-parlor layout', 'Updated chef\'s kitchen', 'Bay windows', 'Landmark district', 'Garden level suite'] },
  { id: 'g-paintedlady-4', cover: 'gen-paintedlady-4', status: 'sale', price: 3200000, beds: 5, baths: 4, sqft: 3800, year: 1905, building: 'Camellia House', address: '770 Queen Anne Ct', city: 'Eureka, CA', type: 'Victorian', agent: 'Priya Anand', desc: 'An impeccably kept Victorian painted lady with ornate gingerbread trim, soaring bay windows and a striking multi-color facade. Period detail meets fully updated systems inside.', features: ['Ornate period millwork', 'Double-parlor layout', 'Updated chef\'s kitchen', 'Bay windows', 'Landmark district', 'Garden level suite'] },
  { id: 'g-brownstone-1', cover: 'gen-brownstone-1', status: 'sale', price: 1850000, beds: 3, baths: 2, sqft: 2600, year: 1890, building: 'Park Slope Brownstone', address: '174 Berkeley Pl', city: 'Brooklyn, NY', type: 'Brownstone', agent: 'Priya Anand', desc: 'A classic brownstone on a tree-lined block with a tall stoop, original plaster moldings and marble mantels. Four stories of flexible living plus a landscaped garden out back.', features: ['Original marble mantels', 'Tall stoop entry', 'Landscaped rear garden', 'Owner\'s triplex potential', 'Crown moldings', 'Rental income unit'] },
  { id: 'g-brownstone-2', cover: 'gen-brownstone-2', status: 'sale', price: 2635000, beds: 4, baths: 3, sqft: 3200, year: 1898, building: 'Clinton Hill Rowhouse', address: '385 Garfield St', city: 'Harlem, NY', type: 'Brownstone', agent: 'Elena Cruz', desc: 'A classic brownstone on a tree-lined block with a tall stoop, original plaster moldings and marble mantels. Four stories of flexible living plus a landscaped garden out back.', features: ['Original marble mantels', 'Tall stoop entry', 'Landscaped rear garden', 'Owner\'s triplex potential', 'Crown moldings', 'Rental income unit'] },
  { id: 'g-brownstone-3', cover: 'gen-brownstone-3', status: 'rent', price: 10150, beds: 5, baths: 4, sqft: 3800, year: 1907, building: 'Stuyvesant Classic', address: '596 Willow Ter', city: 'Hoboken, NJ', type: 'Brownstone Rental', agent: 'Dana Whitmore', desc: 'A classic brownstone on a tree-lined block with a tall stoop, original plaster moldings and marble mantels. Four stories of flexible living plus a landscaped garden out back.', features: ['Original marble mantels', 'Tall stoop entry', 'Landscaped rear garden', 'Owner\'s triplex potential', 'Crown moldings', 'Rental income unit'] },
  { id: 'g-brownstone-4', cover: 'gen-brownstone-4', status: 'sale', price: 4200000, beds: 6, baths: 5, sqft: 4400, year: 1915, building: 'Carroll House', address: '807 Carroll Gdns', city: 'Jersey City, NJ', type: 'Brownstone', agent: 'Marcus Reed', desc: 'A classic brownstone on a tree-lined block with a tall stoop, original plaster moldings and marble mantels. Four stories of flexible living plus a landscaped garden out back.', features: ['Original marble mantels', 'Tall stoop entry', 'Landscaped rear garden', 'Owner\'s triplex potential', 'Crown moldings', 'Rental income unit'] },
  { id: 'g-tudor-1', cover: 'gen-tudor-1', status: 'rent', price: 4200, beds: 4, baths: 3, sqft: 2800, year: 1926, building: 'Heathcote Manor', address: '211 Heathcote Rd', city: 'Scarsdale, NY', type: 'Tudor Revival Rental', agent: 'Marcus Reed', desc: 'A storybook Tudor revival with steep gables, original half-timbering and leaded glass windows. Grand principal rooms, a paneled library and gardens that bloom spring through fall.', features: ['Leaded glass windows', 'Paneled library', 'Slate roof', 'Stone fireplace', 'Butler\'s pantry', 'Mature gardens'] },
  { id: 'g-tudor-2', cover: 'gen-tudor-2', status: 'sale', price: 1295000, beds: 5, baths: 4, sqft: 3400, year: 1931, building: 'The Coventry', address: '422 Coventry Ln', city: 'Shaker Heights, OH', type: 'Tudor Revival', agent: 'Priya Anand', desc: 'A storybook Tudor revival with steep gables, original half-timbering and leaded glass windows. Grand principal rooms, a paneled library and gardens that bloom spring through fall.', features: ['Leaded glass windows', 'Paneled library', 'Slate roof', 'Stone fireplace', 'Butler\'s pantry', 'Mature gardens'] },
  { id: 'g-tudor-3', cover: 'gen-tudor-3', status: 'sale', price: 1695000, beds: 5, baths: 4, sqft: 4000, year: 1935, building: 'Abbey House', address: '633 Abbey Way', city: 'Minneapolis, MN', type: 'Tudor Revival', agent: 'Elena Cruz', desc: 'A storybook Tudor revival with steep gables, original half-timbering and leaded glass windows. Grand principal rooms, a paneled library and gardens that bloom spring through fall.', features: ['Leaded glass windows', 'Paneled library', 'Slate roof', 'Stone fireplace', 'Butler\'s pantry', 'Mature gardens'] },
  { id: 'g-tudor-4', cover: 'gen-tudor-4', status: 'rent', price: 7800, beds: 6, baths: 5, sqft: 4600, year: 1940, building: 'Stonegate Tudor', address: '844 Canterbury Ct', city: 'Grosse Pointe, MI', type: 'Tudor Revival Rental', agent: 'Dana Whitmore', desc: 'A storybook Tudor revival with steep gables, original half-timbering and leaded glass windows. Grand principal rooms, a paneled library and gardens that bloom spring through fall.', features: ['Leaded glass windows', 'Paneled library', 'Slate roof', 'Stone fireplace', 'Butler\'s pantry', 'Mature gardens'] },
  { id: 'g-craftsman-1', cover: 'gen-craftsman-1', status: 'sale', price: 740000, beds: 2, baths: 2, sqft: 1500, year: 1908, building: 'Arroyo Craftsman', address: '248 Arroyo Ter', city: 'Pasadena, CA', type: 'Craftsman', agent: 'Dana Whitmore', desc: 'A lovingly preserved Craftsman bungalow with a deep front porch, tapered columns and quarter-sawn oak built-ins. Warm, light-filled rooms open to a private garden and studio.', features: ['Original built-ins', 'Deep front porch', 'Quarter-sawn oak floors', 'Garden studio', 'Period lighting', 'Updated systems'] },
  { id: 'g-craftsman-2', cover: 'gen-craftsman-2', status: 'rent', price: 4150, beds: 3, baths: 2, sqft: 1870, year: 1914, building: 'The Madrona', address: '459 Madrona Ave', city: 'Portland, OR', type: 'Craftsman Rental', agent: 'Marcus Reed', desc: 'A lovingly preserved Craftsman bungalow with a deep front porch, tapered columns and quarter-sawn oak built-ins. Warm, light-filled rooms open to a private garden and studio.', features: ['Original built-ins', 'Deep front porch', 'Quarter-sawn oak floors', 'Garden studio', 'Period lighting', 'Updated systems'] },
  { id: 'g-craftsman-3', cover: 'gen-craftsman-3', status: 'sale', price: 1215000, beds: 3, baths: 2, sqft: 2230, year: 1919, building: 'Kenilworth Bungalow', address: '670 Kenilworth St', city: 'Asheville, NC', type: 'Craftsman', agent: 'Priya Anand', desc: 'A lovingly preserved Craftsman bungalow with a deep front porch, tapered columns and quarter-sawn oak built-ins. Warm, light-filled rooms open to a private garden and studio.', features: ['Original built-ins', 'Deep front porch', 'Quarter-sawn oak floors', 'Garden studio', 'Period lighting', 'Updated systems'] },
  { id: 'g-craftsman-4', cover: 'gen-craftsman-4', status: 'sale', price: 1450000, beds: 4, baths: 3, sqft: 2600, year: 1925, building: 'Oak Knoll House', address: '881 Bungalow Ct', city: 'Berkeley, CA', type: 'Craftsman', agent: 'Elena Cruz', desc: 'A lovingly preserved Craftsman bungalow with a deep front porch, tapered columns and quarter-sawn oak built-ins. Warm, light-filled rooms open to a private garden and studio.', features: ['Original built-ins', 'Deep front porch', 'Quarter-sawn oak floors', 'Garden studio', 'Period lighting', 'Updated systems'] },
  { id: 'g-capecod-1', cover: 'gen-capecod-1', status: 'sale', price: 980000, beds: 3, baths: 2, sqft: 1800, year: 1948, building: 'Saltbox Cottage', address: '285 Shore Rd', city: 'Chatham, MA', type: 'Coastal Cottage', agent: 'Elena Cruz', desc: 'A weathered-shingle Cape steps from the water, with white trim, hydrangea borders and a sunny rear deck. Crisp coastal interiors and a bunk room made for summer guests.', features: ['Cedar shingle facade', 'Hydrangea gardens', 'Sunny rear deck', 'Bunk room', 'Outdoor shower', 'Walk to beach'] },
  { id: 'g-capecod-2', cover: 'gen-capecod-2', status: 'sale', price: 1455000, beds: 4, baths: 3, sqft: 2270, year: 1967, building: 'Grey Shingles', address: '496 Lighthouse Ln', city: 'Nantucket, MA', type: 'Coastal Cottage', agent: 'Dana Whitmore', desc: 'A weathered-shingle Cape steps from the water, with white trim, hydrangea borders and a sunny rear deck. Crisp coastal interiors and a bunk room made for summer guests.', features: ['Cedar shingle facade', 'Hydrangea gardens', 'Sunny rear deck', 'Bunk room', 'Outdoor shower', 'Walk to beach'] },
  { id: 'g-capecod-3', cover: 'gen-capecod-3', status: 'rent', price: 7600, beds: 4, baths: 3, sqft: 2730, year: 1986, building: 'Harbor Cottage', address: '707 Salt Marsh Way', city: 'Kennebunkport, ME', type: 'Coastal Cottage Rental', agent: 'Marcus Reed', desc: 'A weathered-shingle Cape steps from the water, with white trim, hydrangea borders and a sunny rear deck. Crisp coastal interiors and a bunk room made for summer guests.', features: ['Cedar shingle facade', 'Hydrangea gardens', 'Sunny rear deck', 'Bunk room', 'Outdoor shower', 'Walk to beach'] },
  { id: 'g-capecod-4', cover: 'gen-capecod-4', status: 'sale', price: 2400000, beds: 5, baths: 4, sqft: 3200, year: 2005, building: 'The Widow\'s Walk', address: '918 Harborview Dr', city: 'Madison, CT', type: 'Coastal Cottage', agent: 'Priya Anand', desc: 'A weathered-shingle Cape steps from the water, with white trim, hydrangea borders and a sunny rear deck. Crisp coastal interiors and a bunk room made for summer guests.', features: ['Cedar shingle facade', 'Hydrangea gardens', 'Sunny rear deck', 'Bunk room', 'Outdoor shower', 'Walk to beach'] },
  { id: 'g-greekrevival-1', cover: 'gen-greekrevival-1', status: 'rent', price: 7500, beds: 4, baths: 3, sqft: 4000, year: 1840, building: 'Monterey House', address: '322 Monterey Sq', city: 'Savannah, GA', type: 'Historic Estate Rental', agent: 'Priya Anand', desc: 'A commanding Greek revival with double gallery porches, soaring columns and original heart-pine floors, shaded by live oaks draped in Spanish moss. History with every modern comfort.', features: ['Double gallery porches', 'Heart-pine floors', '14-foot ceilings', 'Carriage house', 'Walled courtyard', 'Historic district'] },
  { id: 'g-greekrevival-2', cover: 'gen-greekrevival-2', status: 'sale', price: 2400000, beds: 5, baths: 4, sqft: 5070, year: 1850, building: 'The Columns', address: '533 Legare St', city: 'Charleston, SC', type: 'Historic Estate', agent: 'Elena Cruz', desc: 'A commanding Greek revival with double gallery porches, soaring columns and original heart-pine floors, shaded by live oaks draped in Spanish moss. History with every modern comfort.', features: ['Double gallery porches', 'Heart-pine floors', '14-foot ceilings', 'Carriage house', 'Walled courtyard', 'Historic district'] },
  { id: 'g-greekrevival-3', cover: 'gen-greekrevival-3', status: 'sale', price: 3150000, beds: 6, baths: 5, sqft: 6130, year: 1860, building: 'Camellia Hall', address: '744 Camellia Ave', city: 'Natchez, MS', type: 'Historic Estate', agent: 'Dana Whitmore', desc: 'A commanding Greek revival with double gallery porches, soaring columns and original heart-pine floors, shaded by live oaks draped in Spanish moss. History with every modern comfort.', features: ['Double gallery porches', 'Heart-pine floors', '14-foot ceilings', 'Carriage house', 'Walled courtyard', 'Historic district'] },
  { id: 'g-greekrevival-4', cover: 'gen-greekrevival-4', status: 'rent', price: 14000, beds: 7, baths: 6, sqft: 7200, year: 1870, building: 'Oak Alley House', address: '955 Antebellum Way', city: 'Madison, GA', type: 'Historic Estate Rental', agent: 'Marcus Reed', desc: 'A commanding Greek revival with double gallery porches, soaring columns and original heart-pine floors, shaded by live oaks draped in Spanish moss. History with every modern comfort.', features: ['Double gallery porches', 'Heart-pine floors', '14-foot ceilings', 'Carriage house', 'Walled courtyard', 'Historic district'] },
  { id: 'g-adobe-1', cover: 'gen-adobe-1', status: 'sale', price: 720000, beds: 2, baths: 2, sqft: 1700, year: 1975, building: 'Casa Encantada', address: '359 Camino Encantado', city: 'Santa Fe, NM', type: 'Pueblo Adobe', agent: 'Marcus Reed', desc: 'An authentic pueblo-style adobe with hand-plastered walls, exposed vigas and kiva fireplaces. Portals and courtyards frame mountain views and glowing high-desert sunsets.', features: ['Kiva fireplaces', 'Exposed vigas', 'Hand-plastered walls', 'Courtyard portal', 'Radiant floors', 'Mountain views'] },
  { id: 'g-adobe-2', cover: 'gen-adobe-2', status: 'rent', price: 4550, beds: 3, baths: 2, sqft: 2200, year: 1988, building: 'Adobe del Sol', address: '570 Vista del Sol', city: 'Taos, NM', type: 'Pueblo Adobe Rental', agent: 'Priya Anand', desc: 'An authentic pueblo-style adobe with hand-plastered walls, exposed vigas and kiva fireplaces. Portals and courtyards frame mountain views and glowing high-desert sunsets.', features: ['Kiva fireplaces', 'Exposed vigas', 'Hand-plastered walls', 'Courtyard portal', 'Radiant floors', 'Mountain views'] },
  { id: 'g-adobe-3', cover: 'gen-adobe-3', status: 'sale', price: 1475000, beds: 3, baths: 2, sqft: 2700, year: 2002, building: 'Kiva House', address: '781 Kiva Ct', city: 'Albuquerque, NM', type: 'Pueblo Adobe', agent: 'Elena Cruz', desc: 'An authentic pueblo-style adobe with hand-plastered walls, exposed vigas and kiva fireplaces. Portals and courtyards frame mountain views and glowing high-desert sunsets.', features: ['Kiva fireplaces', 'Exposed vigas', 'Hand-plastered walls', 'Courtyard portal', 'Radiant floors', 'Mountain views'] },
  { id: 'g-adobe-4', cover: 'gen-adobe-4', status: 'sale', price: 1850000, beds: 4, baths: 3, sqft: 3200, year: 2015, building: 'Casa Coyote', address: '992 Coyote Trail', city: 'Sedona, AZ', type: 'Pueblo Adobe', agent: 'Dana Whitmore', desc: 'An authentic pueblo-style adobe with hand-plastered walls, exposed vigas and kiva fireplaces. Portals and courtyards frame mountain views and glowing high-desert sunsets.', features: ['Kiva fireplaces', 'Exposed vigas', 'Hand-plastered walls', 'Courtyard portal', 'Radiant floors', 'Mountain views'] },
  { id: 'g-medvilla-1', cover: 'gen-medvilla-1', status: 'sale', price: 1450000, beds: 4, baths: 3, sqft: 3400, year: 1998, building: 'Villa Toscana', address: '396 Via Toscana', city: 'Naples, FL', type: 'Mediterranean Villa', agent: 'Dana Whitmore', desc: 'A grand Mediterranean villa with a barrel-tile roof, arched loggias and a fountain courtyard. Resort grounds with a pool, summer kitchen and lush tropical privacy hedges.', features: ['Fountain courtyard', 'Arched loggias', 'Pool & summer kitchen', 'Wine room', '3-car garage', 'Tropical landscaping'] },
  { id: 'g-medvilla-2', cover: 'gen-medvilla-2', status: 'sale', price: 2165000, beds: 5, baths: 4, sqft: 4270, year: 2005, building: 'Palma Vista', address: '607 Palma Vista Ct', city: 'Boca Raton, FL', type: 'Mediterranean Villa', agent: 'Marcus Reed', desc: 'A grand Mediterranean villa with a barrel-tile roof, arched loggias and a fountain courtyard. Resort grounds with a pool, summer kitchen and lush tropical privacy hedges.', features: ['Fountain courtyard', 'Arched loggias', 'Pool & summer kitchen', 'Wine room', '3-car garage', 'Tropical landscaping'] },
  { id: 'g-medvilla-3', cover: 'gen-medvilla-3', status: 'rent', price: 11350, beds: 5, baths: 4, sqft: 5130, year: 2013, building: 'Bella Riva', address: '818 Bella Riva Dr', city: 'Coral Gables, FL', type: 'Mediterranean Villa Rental', agent: 'Priya Anand', desc: 'A grand Mediterranean villa with a barrel-tile roof, arched loggias and a fountain courtyard. Resort grounds with a pool, summer kitchen and lush tropical privacy hedges.', features: ['Fountain courtyard', 'Arched loggias', 'Pool & summer kitchen', 'Wine room', '3-car garage', 'Tropical landscaping'] },
  { id: 'g-medvilla-4', cover: 'gen-medvilla-4', status: 'sale', price: 3600000, beds: 6, baths: 5, sqft: 6000, year: 2020, building: 'Casa Verde', address: '1029 Isla Verde Way', city: 'Sarasota, FL', type: 'Mediterranean Villa', agent: 'Elena Cruz', desc: 'A grand Mediterranean villa with a barrel-tile roof, arched loggias and a fountain courtyard. Resort grounds with a pool, summer kitchen and lush tropical privacy hedges.', features: ['Fountain courtyard', 'Arched loggias', 'Pool & summer kitchen', 'Wine room', '3-car garage', 'Tropical landscaping'] },
  { id: 'g-chateau-1', cover: 'gen-chateau-1', status: 'sale', price: 2400000, beds: 5, baths: 4, sqft: 6000, year: 2001, building: 'Chateau Lumiere', address: '433 Versailles Ct', city: 'Dallas, TX', type: 'French Chateau', agent: 'Elena Cruz', desc: 'A limestone French chateau with a slate mansard roof, iron balconies and formal parterre gardens. Gallery halls, a paneled study and entertaining rooms of rare scale.', features: ['Limestone facade', 'Slate mansard roof', 'Formal gardens', 'Paneled study', 'Wine cellar', 'Gated motor court'] },
  { id: 'g-chateau-2', cover: 'gen-chateau-2', status: 'sale', price: 3535000, beds: 6, baths: 5, sqft: 7670, year: 2008, building: 'Maison Loire', address: '644 Loire Ln', city: 'Great Falls, VA', type: 'French Chateau', agent: 'Dana Whitmore', desc: 'A limestone French chateau with a slate mansard roof, iron balconies and formal parterre gardens. Gallery halls, a paneled study and entertaining rooms of rare scale.', features: ['Limestone facade', 'Slate mansard roof', 'Formal gardens', 'Paneled study', 'Wine cellar', 'Gated motor court'] },
  { id: 'g-chateau-3', cover: 'gen-chateau-3', status: 'sale', price: 4665000, beds: 7, baths: 6, sqft: 9330, year: 2015, building: 'Normandy Hall', address: '855 Chateau Ridge', city: 'Lake Forest, IL', type: 'French Chateau', agent: 'Marcus Reed', desc: 'A limestone French chateau with a slate mansard roof, iron balconies and formal parterre gardens. Gallery halls, a paneled study and entertaining rooms of rare scale.', features: ['Limestone facade', 'Slate mansard roof', 'Formal gardens', 'Paneled study', 'Wine cellar', 'Gated motor court'] },
  { id: 'g-chateau-4', cover: 'gen-chateau-4', status: 'rent', price: 20000, beds: 8, baths: 6, sqft: 11000, year: 2022, building: 'Petit Chateau', address: '1066 Normandy Pl', city: 'Brentwood, TN', type: 'French Chateau Rental', agent: 'Priya Anand', desc: 'A limestone French chateau with a slate mansard roof, iron balconies and formal parterre gardens. Gallery halls, a paneled study and entertaining rooms of rare scale.', features: ['Limestone facade', 'Slate mansard roof', 'Formal gardens', 'Paneled study', 'Wine cellar', 'Gated motor court'] },
  { id: 'g-logcabin-1', cover: 'gen-logcabin-1', status: 'rent', price: 3200, beds: 2, baths: 2, sqft: 1400, year: 1992, building: 'Elk Meadow Lodge', address: '470 Elk Meadow Rd', city: 'Whitefish, MT', type: 'Log Cabin Rental', agent: 'Priya Anand', desc: 'A hand-hewn log home with a river-rock chimney, vaulted great room and wide porches overlooking meadow and timber. Built for four-season mountain living.', features: ['Hand-hewn logs', 'River-rock fireplace', 'Vaulted great room', 'Wraparound porch', 'Acreage with trees', 'Trail access'] },
  { id: 'g-logcabin-2', cover: 'gen-logcabin-2', status: 'sale', price: 1035000, beds: 3, baths: 2, sqft: 2070, year: 2001, building: 'Timberline Cabin', address: '681 Timberline Trl', city: 'Jackson, WY', type: 'Log Cabin', agent: 'Elena Cruz', desc: 'A hand-hewn log home with a river-rock chimney, vaulted great room and wide porches overlooking meadow and timber. Built for four-season mountain living.', features: ['Hand-hewn logs', 'River-rock fireplace', 'Vaulted great room', 'Wraparound porch', 'Acreage with trees', 'Trail access'] },
  { id: 'g-logcabin-3', cover: 'gen-logcabin-3', status: 'sale', price: 1395000, beds: 4, baths: 3, sqft: 2730, year: 2009, building: 'Grizzly Lodge', address: '892 Grizzly Bend', city: 'Coeur d\'Alene, ID', type: 'Log Cabin', agent: 'Dana Whitmore', desc: 'A hand-hewn log home with a river-rock chimney, vaulted great room and wide porches overlooking meadow and timber. Built for four-season mountain living.', features: ['Hand-hewn logs', 'River-rock fireplace', 'Vaulted great room', 'Wraparound porch', 'Acreage with trees', 'Trail access'] },
  { id: 'g-logcabin-4', cover: 'gen-logcabin-4', status: 'sale', price: 1750000, beds: 5, baths: 4, sqft: 3400, year: 2018, building: 'Lodgepole House', address: '1103 Lodgepole Ln', city: 'Estes Park, CO', type: 'Log Cabin', agent: 'Marcus Reed', desc: 'A hand-hewn log home with a river-rock chimney, vaulted great room and wide porches overlooking meadow and timber. Built for four-season mountain living.', features: ['Hand-hewn logs', 'River-rock fireplace', 'Vaulted great room', 'Wraparound porch', 'Acreage with trees', 'Trail access'] },
  { id: 'g-aframe-1', cover: 'gen-aframe-1', status: 'sale', price: 420000, beds: 1, baths: 1, sqft: 900, year: 1968, building: 'The Snowridge', address: '507 Snowridge Rd', city: 'Big Bear Lake, CA', type: 'A-Frame Cabin', agent: 'Marcus Reed', desc: 'An iconic A-frame tucked into the evergreens, with a wall of glass at the gable, a wood stove and a loft bedroom under the rafters. Deck living in every season.', features: ['Floor-to-peak windows', 'Sleeping loft', 'Wood stove', 'Wraparound deck', 'Fire pit', 'Near slopes & trails'] },
  { id: 'g-aframe-2', cover: 'gen-aframe-2', status: 'rent', price: 2850, beds: 2, baths: 2, sqft: 1200, year: 1986, building: 'Alpine A-Frame', address: '718 Alpine Way', city: 'Leavenworth, WA', type: 'A-Frame Cabin Rental', agent: 'Priya Anand', desc: 'An iconic A-frame tucked into the evergreens, with a wall of glass at the gable, a wood stove and a loft bedroom under the rafters. Deck living in every season.', features: ['Floor-to-peak windows', 'Sleeping loft', 'Wood stove', 'Wraparound deck', 'Fire pit', 'Near slopes & trails'] },
  { id: 'g-aframe-3', cover: 'gen-aframe-3', status: 'sale', price: 735000, beds: 2, baths: 2, sqft: 1500, year: 2003, building: 'Fir Haus', address: '929 Fir Tree Ln', city: 'Gatlinburg, TN', type: 'A-Frame Cabin', agent: 'Elena Cruz', desc: 'An iconic A-frame tucked into the evergreens, with a wall of glass at the gable, a wood stove and a loft bedroom under the rafters. Deck living in every season.', features: ['Floor-to-peak windows', 'Sleeping loft', 'Wood stove', 'Wraparound deck', 'Fire pit', 'Near slopes & trails'] },
  { id: 'g-aframe-4', cover: 'gen-aframe-4', status: 'sale', price: 890000, beds: 3, baths: 2, sqft: 1800, year: 2021, building: 'Summit Chalet', address: '1140 Summit Loop', city: 'Lake Placid, NY', type: 'A-Frame Cabin', agent: 'Dana Whitmore', desc: 'An iconic A-frame tucked into the evergreens, with a wall of glass at the gable, a wood stove and a loft bedroom under the rafters. Deck living in every season.', features: ['Floor-to-peak windows', 'Sleeping loft', 'Wood stove', 'Wraparound deck', 'Fire pit', 'Near slopes & trails'] },
  { id: 'g-glassbox-1', cover: 'gen-glassbox-1', status: 'sale', price: 1650000, beds: 3, baths: 2, sqft: 2600, year: 2016, building: 'The Glass Pavilion', address: '544 Skyline Blvd', city: 'Portland, OR', type: 'Modern Architectural', agent: 'Dana Whitmore', desc: 'A cantilevered glass-and-steel residence floating over the hillside, with frameless walls of glass, floating stairs and terraces that dissolve into the treetops.', features: ['Cantilevered design', 'Frameless glass walls', 'Floating staircase', 'Infinity terrace', 'Architect-designed', 'Panoramic views'] },
  { id: 'g-glassbox-2', cover: 'gen-glassbox-2', status: 'sale', price: 2365000, beds: 4, baths: 3, sqft: 3330, year: 2019, building: 'Ridgecrest House', address: '755 Ridgecrest Dr', city: 'Austin, TX', type: 'Modern Architectural', agent: 'Marcus Reed', desc: 'A cantilevered glass-and-steel residence floating over the hillside, with frameless walls of glass, floating stairs and terraces that dissolve into the treetops.', features: ['Cantilevered design', 'Frameless glass walls', 'Floating staircase', 'Infinity terrace', 'Architect-designed', 'Panoramic views'] },
  { id: 'g-glassbox-3', cover: 'gen-glassbox-3', status: 'rent', price: 11050, beds: 4, baths: 3, sqft: 4070, year: 2021, building: 'Canyon Edge', address: '966 Canyon Edge Rd', city: 'Asheville, NC', type: 'Modern Architectural Rental', agent: 'Priya Anand', desc: 'A cantilevered glass-and-steel residence floating over the hillside, with frameless walls of glass, floating stairs and terraces that dissolve into the treetops.', features: ['Cantilevered design', 'Frameless glass walls', 'Floating staircase', 'Infinity terrace', 'Architect-designed', 'Panoramic views'] },
  { id: 'g-glassbox-4', cover: 'gen-glassbox-4', status: 'sale', price: 3800000, beds: 5, baths: 4, sqft: 4800, year: 2024, building: 'Overlook Residence', address: '1177 Overlook Ter', city: 'Topanga, CA', type: 'Modern Architectural', agent: 'Elena Cruz', desc: 'A cantilevered glass-and-steel residence floating over the hillside, with frameless walls of glass, floating stairs and terraces that dissolve into the treetops.', features: ['Cantilevered design', 'Frameless glass walls', 'Floating staircase', 'Infinity terrace', 'Architect-designed', 'Panoramic views'] },
  { id: 'g-brutalist-1', cover: 'gen-brutalist-1', status: 'rent', price: 6000, beds: 3, baths: 2, sqft: 2800, year: 2014, building: 'The Monolith', address: '581 Monolith Way', city: 'Los Angeles, CA', type: 'Brutalist Modern Rental', agent: 'Elena Cruz', desc: 'A sculptural board-formed concrete home with monumental volumes, skylit galleries and warm walnut interiors that soften the raw structure. A private, gallery-like retreat.', features: ['Board-formed concrete', 'Skylit gallery hall', 'Walnut interiors', 'Courtyard pool', 'Radiant floors', 'Gated entry'] },
  { id: 'g-brutalist-2', cover: 'gen-brutalist-2', status: 'sale', price: 2000000, beds: 4, baths: 3, sqft: 3600, year: 2017, building: 'Cast House', address: '792 Cast Stone Ct', city: 'Phoenix, AZ', type: 'Brutalist Modern', agent: 'Dana Whitmore', desc: 'A sculptural board-formed concrete home with monumental volumes, skylit galleries and warm walnut interiors that soften the raw structure. A private, gallery-like retreat.', features: ['Board-formed concrete', 'Skylit gallery hall', 'Walnut interiors', 'Courtyard pool', 'Radiant floors', 'Gated entry'] },
  { id: 'g-brutalist-3', cover: 'gen-brutalist-3', status: 'sale', price: 2600000, beds: 4, baths: 3, sqft: 4400, year: 2020, building: 'Formline Residence', address: '1003 Form Line Dr', city: 'Dallas, TX', type: 'Brutalist Modern', agent: 'Marcus Reed', desc: 'A sculptural board-formed concrete home with monumental volumes, skylit galleries and warm walnut interiors that soften the raw structure. A private, gallery-like retreat.', features: ['Board-formed concrete', 'Skylit gallery hall', 'Walnut interiors', 'Courtyard pool', 'Radiant floors', 'Gated entry'] },
  { id: 'g-brutalist-4', cover: 'gen-brutalist-4', status: 'rent', price: 11000, beds: 5, baths: 4, sqft: 5200, year: 2023, building: 'Grey Ridge House', address: '1214 Grey Ridge Rd', city: 'Denver, CO', type: 'Brutalist Modern Rental', agent: 'Priya Anand', desc: 'A sculptural board-formed concrete home with monumental volumes, skylit galleries and warm walnut interiors that soften the raw structure. A private, gallery-like retreat.', features: ['Board-formed concrete', 'Skylit gallery hall', 'Walnut interiors', 'Courtyard pool', 'Radiant floors', 'Gated entry'] },
  { id: 'g-scandi-1', cover: 'gen-scandi-1', status: 'sale', price: 890000, beds: 2, baths: 2, sqft: 1800, year: 2017, building: 'Svarthus', address: '618 Birchwood Ln', city: 'Hudson, NY', type: 'Scandinavian Modern', agent: 'Priya Anand', desc: 'A black-stained timber house with a crisp gabled silhouette, white-oak interiors and triple-glazed windows framing the woods. Hygge, engineered to passive-house standards.', features: ['Black timber cladding', 'White oak interiors', 'Passive-house build', 'Sauna', 'Triple-glazed windows', 'Forested lot'] },
  { id: 'g-scandi-2', cover: 'gen-scandi-2', status: 'rent', price: 5300, beds: 3, baths: 2, sqft: 2270, year: 2019, building: 'Fjord House', address: '829 Fjord View Rd', city: 'Woodstock, VT', type: 'Scandinavian Modern Rental', agent: 'Elena Cruz', desc: 'A black-stained timber house with a crisp gabled silhouette, white-oak interiors and triple-glazed windows framing the woods. Hygge, engineered to passive-house standards.', features: ['Black timber cladding', 'White oak interiors', 'Passive-house build', 'Sauna', 'Triple-glazed windows', 'Forested lot'] },
  { id: 'g-scandi-3', cover: 'gen-scandi-3', status: 'sale', price: 1595000, beds: 3, baths: 2, sqft: 2730, year: 2022, building: 'Nordic Retreat', address: '1040 Nordic Way', city: 'Bend, OR', type: 'Scandinavian Modern', agent: 'Dana Whitmore', desc: 'A black-stained timber house with a crisp gabled silhouette, white-oak interiors and triple-glazed windows framing the woods. Hygge, engineered to passive-house standards.', features: ['Black timber cladding', 'White oak interiors', 'Passive-house build', 'Sauna', 'Triple-glazed windows', 'Forested lot'] },
  { id: 'g-scandi-4', cover: 'gen-scandi-4', status: 'sale', price: 1950000, beds: 4, baths: 3, sqft: 3200, year: 2024, building: 'Larch House', address: '1251 Larch Hollow', city: 'Duluth, MN', type: 'Scandinavian Modern', agent: 'Marcus Reed', desc: 'A black-stained timber house with a crisp gabled silhouette, white-oak interiors and triple-glazed windows framing the woods. Hygge, engineered to passive-house standards.', features: ['Black timber cladding', 'White oak interiors', 'Passive-house build', 'Sauna', 'Triple-glazed windows', 'Forested lot'] },
  { id: 'g-modfarm-1', cover: 'gen-modfarm-1', status: 'sale', price: 640000, beds: 3, baths: 2, sqft: 2200, year: 2017, building: 'Harvest House', address: '655 Harvest Ln', city: 'Franklin, TN', type: 'Modern Farmhouse', agent: 'Marcus Reed', desc: 'A crisp modern farmhouse with board-and-batten siding, a standing-seam metal roof and a wraparound porch. Shiplap, wide-plank oak and a showpiece kitchen inside.', features: ['Wraparound porch', 'Standing-seam roof', 'Showpiece kitchen', 'Shiplap detailing', 'Mudroom & drop zone', 'Level backyard'] },
  { id: 'g-modfarm-2', cover: 'gen-modfarm-2', status: 'sale', price: 875000, beds: 4, baths: 3, sqft: 2800, year: 2019, building: 'Silo Bend Farm', address: '866 Silo Bend', city: 'Waco, TX', type: 'Modern Farmhouse', agent: 'Priya Anand', desc: 'A crisp modern farmhouse with board-and-batten siding, a standing-seam metal roof and a wraparound porch. Shiplap, wide-plank oak and a showpiece kitchen inside.', features: ['Wraparound porch', 'Standing-seam roof', 'Showpiece kitchen', 'Shiplap detailing', 'Mudroom & drop zone', 'Level backyard'] },
  { id: 'g-modfarm-3', cover: 'gen-modfarm-3', status: 'rent', price: 4950, beds: 4, baths: 3, sqft: 3400, year: 2022, building: 'Meadowbrook', address: '1077 Meadowbrook Rd', city: 'Greenville, SC', type: 'Modern Farmhouse Rental', agent: 'Elena Cruz', desc: 'A crisp modern farmhouse with board-and-batten siding, a standing-seam metal roof and a wraparound porch. Shiplap, wide-plank oak and a showpiece kitchen inside.', features: ['Wraparound porch', 'Standing-seam roof', 'Showpiece kitchen', 'Shiplap detailing', 'Mudroom & drop zone', 'Level backyard'] },
  { id: 'g-modfarm-4', cover: 'gen-modfarm-4', status: 'sale', price: 1350000, beds: 5, baths: 4, sqft: 4000, year: 2024, building: 'White Barn', address: '1288 White Barn Ct', city: 'McKinney, TX', type: 'Modern Farmhouse', agent: 'Dana Whitmore', desc: 'A crisp modern farmhouse with board-and-batten siding, a standing-seam metal roof and a wraparound porch. Shiplap, wide-plank oak and a showpiece kitchen inside.', features: ['Wraparound porch', 'Standing-seam roof', 'Showpiece kitchen', 'Shiplap detailing', 'Mudroom & drop zone', 'Level backyard'] },
  { id: 'g-desertmod-1', cover: 'gen-desertmod-1', status: 'rent', price: 5500, beds: 3, baths: 2, sqft: 2600, year: 2015, building: 'Saguaro House', address: '692 Saguaro Vista', city: 'Scottsdale, AZ', type: 'Desert Contemporary Rental', agent: 'Dana Whitmore', desc: 'A low-slung desert contemporary of rammed earth and glass, oriented to mountain silhouettes and saguaro-studded grounds. Deep overhangs, a negative-edge pool and starlit patios.', features: ['Rammed-earth walls', 'Negative-edge pool', 'Deep shade overhangs', 'Desert landscaping', 'Owned solar', 'Mountain views'] },
  { id: 'g-desertmod-2', cover: 'gen-desertmod-2', status: 'sale', price: 1865000, beds: 4, baths: 3, sqft: 3330, year: 2018, building: 'Ocotillo Residence', address: '903 Ocotillo Rdg', city: 'Paradise Valley, AZ', type: 'Desert Contemporary', agent: 'Marcus Reed', desc: 'A low-slung desert contemporary of rammed earth and glass, oriented to mountain silhouettes and saguaro-studded grounds. Deep overhangs, a negative-edge pool and starlit patios.', features: ['Rammed-earth walls', 'Negative-edge pool', 'Deep shade overhangs', 'Desert landscaping', 'Owned solar', 'Mountain views'] },
  { id: 'g-desertmod-3', cover: 'gen-desertmod-3', status: 'sale', price: 2485000, beds: 4, baths: 3, sqft: 4070, year: 2021, building: 'Mesa Shadow', address: '1114 Mesa Shadow Dr', city: 'Palm Desert, CA', type: 'Desert Contemporary', agent: 'Priya Anand', desc: 'A low-slung desert contemporary of rammed earth and glass, oriented to mountain silhouettes and saguaro-studded grounds. Deep overhangs, a negative-edge pool and starlit patios.', features: ['Rammed-earth walls', 'Negative-edge pool', 'Deep shade overhangs', 'Desert landscaping', 'Owned solar', 'Mountain views'] },
  { id: 'g-desertmod-4', cover: 'gen-desertmod-4', status: 'rent', price: 10500, beds: 5, baths: 4, sqft: 4800, year: 2024, building: 'Ironwood Modern', address: '1325 Ironwood Ct', city: 'St. George, UT', type: 'Desert Contemporary Rental', agent: 'Elena Cruz', desc: 'A low-slung desert contemporary of rammed earth and glass, oriented to mountain silhouettes and saguaro-studded grounds. Deep overhangs, a negative-edge pool and starlit patios.', features: ['Rammed-earth walls', 'Negative-edge pool', 'Deep shade overhangs', 'Desert landscaping', 'Owned solar', 'Mountain views'] },
  { id: 'g-stiltbeach-1', cover: 'gen-stiltbeach-1', status: 'sale', price: 780000, beds: 3, baths: 2, sqft: 1800, year: 2005, building: 'Sandpiper Stilts', address: '729 Sandpiper Ln', city: 'Outer Banks, NC', type: 'Beach House', agent: 'Elena Cruz', desc: 'An elevated beach house with panoramic decks, a breezy open great room and boardwalk access to the sand. Hurricane-rated build with room for the whole crew underneath.', features: ['Elevated pilings', 'Panoramic decks', 'Boardwalk to beach', 'Outdoor shower', 'Impact windows', 'Rental history'] },
  { id: 'g-stiltbeach-2', cover: 'gen-stiltbeach-2', status: 'rent', price: 5350, beds: 4, baths: 3, sqft: 2400, year: 2011, building: 'Dune Crest', address: '940 Dune Crest Rd', city: 'Galveston, TX', type: 'Beach House Rental', agent: 'Dana Whitmore', desc: 'An elevated beach house with panoramic decks, a breezy open great room and boardwalk access to the sand. Hurricane-rated build with room for the whole crew underneath.', features: ['Elevated pilings', 'Panoramic decks', 'Boardwalk to beach', 'Outdoor shower', 'Impact windows', 'Rental history'] },
  { id: 'g-stiltbeach-3', cover: 'gen-stiltbeach-3', status: 'sale', price: 1560000, beds: 5, baths: 4, sqft: 3000, year: 2016, building: 'Pelican Watch', address: '1151 Pelican Watch', city: 'Folly Beach, SC', type: 'Beach House', agent: 'Marcus Reed', desc: 'An elevated beach house with panoramic decks, a breezy open great room and boardwalk access to the sand. Hurricane-rated build with room for the whole crew underneath.', features: ['Elevated pilings', 'Panoramic decks', 'Boardwalk to beach', 'Outdoor shower', 'Impact windows', 'Rental history'] },
  { id: 'g-stiltbeach-4', cover: 'gen-stiltbeach-4', status: 'sale', price: 1950000, beds: 6, baths: 5, sqft: 3600, year: 2022, building: 'Sea Oats House', address: '1362 Sea Oats Ct', city: 'Gulf Shores, AL', type: 'Beach House', agent: 'Priya Anand', desc: 'An elevated beach house with panoramic decks, a breezy open great room and boardwalk access to the sand. Hurricane-rated build with room for the whole crew underneath.', features: ['Elevated pilings', 'Panoramic decks', 'Boardwalk to beach', 'Outdoor shower', 'Impact windows', 'Rental history'] },
  { id: 'g-tropical-1', cover: 'gen-tropical-1', status: 'sale', price: 1950000, beds: 4, baths: 3, sqft: 3400, year: 2016, building: 'Palm Isle Villa', address: '766 Palm Isle Dr', city: 'Miami, FL', type: 'Tropical Modern', agent: 'Priya Anand', desc: 'A tropical modern villa where sliding glass walls open to an infinity pool and palm-shaded lanais. Indoor-outdoor living with a summer kitchen and lush resort grounds.', features: ['Infinity-edge pool', 'Disappearing glass walls', 'Covered lanai', 'Summer kitchen', 'Smart home', 'Dock access'] },
  { id: 'g-tropical-2', cover: 'gen-tropical-2', status: 'sale', price: 2900000, beds: 5, baths: 4, sqft: 4330, year: 2019, building: 'Lagoon House', address: '977 Lagoon Vista', city: 'Kailua, HI', type: 'Tropical Modern', agent: 'Elena Cruz', desc: 'A tropical modern villa where sliding glass walls open to an infinity pool and palm-shaded lanais. Indoor-outdoor living with a summer kitchen and lush resort grounds.', features: ['Infinity-edge pool', 'Disappearing glass walls', 'Covered lanai', 'Summer kitchen', 'Smart home', 'Dock access'] },
  { id: 'g-tropical-3', cover: 'gen-tropical-3', status: 'rent', price: 15000, beds: 5, baths: 4, sqft: 5270, year: 2021, building: 'Banyan Cove', address: '1188 Banyan Cove', city: 'Key Largo, FL', type: 'Tropical Modern Rental', agent: 'Dana Whitmore', desc: 'A tropical modern villa where sliding glass walls open to an infinity pool and palm-shaded lanais. Indoor-outdoor living with a summer kitchen and lush resort grounds.', features: ['Infinity-edge pool', 'Disappearing glass walls', 'Covered lanai', 'Summer kitchen', 'Smart home', 'Dock access'] },
  { id: 'g-tropical-4', cover: 'gen-tropical-4', status: 'sale', price: 4800000, beds: 6, baths: 5, sqft: 6200, year: 2024, building: 'Coconut Grove Villa', address: '1399 Coconut Row', city: 'Fort Lauderdale, FL', type: 'Tropical Modern', agent: 'Marcus Reed', desc: 'A tropical modern villa where sliding glass walls open to an infinity pool and palm-shaded lanais. Indoor-outdoor living with a summer kitchen and lush resort grounds.', features: ['Infinity-edge pool', 'Disappearing glass walls', 'Covered lanai', 'Summer kitchen', 'Smart home', 'Dock access'] },
  { id: 'g-spanishcol-1', cover: 'gen-spanishcol-1', status: 'sale', price: 1750000, beds: 3, baths: 2, sqft: 2800, year: 1925, building: 'Casa Cielo', address: '803 Camino Cielo', city: 'Santa Barbara, CA', type: 'Spanish Colonial', agent: 'Marcus Reed', desc: 'A romantic Spanish colonial with white stucco walls, a red-tile roof and hand-painted tile stair risers. Wrought-iron balconies and a bougainvillea courtyard with fountain.', features: ['Tiled courtyard fountain', 'Hand-painted tile', 'Wrought-iron balconies', 'Beamed ceilings', 'Ocean glimpses', 'Citrus garden'] },
  { id: 'g-spanishcol-2', cover: 'gen-spanishcol-2', status: 'sale', price: 2565000, beds: 4, baths: 3, sqft: 3670, year: 1953, building: 'Mission Ridge', address: '1014 Mission Ridge Rd', city: 'San Clemente, CA', type: 'Spanish Colonial', agent: 'Priya Anand', desc: 'A romantic Spanish colonial with white stucco walls, a red-tile roof and hand-painted tile stair risers. Wrought-iron balconies and a bougainvillea courtyard with fountain.', features: ['Tiled courtyard fountain', 'Hand-painted tile', 'Wrought-iron balconies', 'Beamed ceilings', 'Ocean glimpses', 'Citrus garden'] },
  { id: 'g-spanishcol-3', cover: 'gen-spanishcol-3', status: 'sale', price: 3385000, beds: 5, baths: 4, sqft: 4530, year: 1982, building: 'Las Palmas', address: '1225 Las Palmas Dr', city: 'Ojai, CA', type: 'Spanish Colonial', agent: 'Elena Cruz', desc: 'A romantic Spanish colonial with white stucco walls, a red-tile roof and hand-painted tile stair risers. Wrought-iron balconies and a bougainvillea courtyard with fountain.', features: ['Tiled courtyard fountain', 'Hand-painted tile', 'Wrought-iron balconies', 'Beamed ceilings', 'Ocean glimpses', 'Citrus garden'] },
  { id: 'g-spanishcol-4', cover: 'gen-spanishcol-4', status: 'rent', price: 14500, beds: 6, baths: 5, sqft: 5400, year: 2010, building: 'El Encanto', address: '1436 El Encanto Way', city: 'La Jolla, CA', type: 'Spanish Colonial Rental', agent: 'Dana Whitmore', desc: 'A romantic Spanish colonial with white stucco walls, a red-tile roof and hand-painted tile stair risers. Wrought-iron balconies and a bougainvillea courtyard with fountain.', features: ['Tiled courtyard fountain', 'Hand-painted tile', 'Wrought-iron balconies', 'Beamed ceilings', 'Ocean glimpses', 'Citrus garden'] },
  { id: 'g-georgian-1', cover: 'gen-georgian-1', status: 'rent', price: 10000, beds: 5, baths: 4, sqft: 5200, year: 1928, building: 'Round Hill Manor', address: '840 Round Hill Rd', city: 'Greenwich, CT', type: 'Georgian Manor Rental', agent: 'Dana Whitmore', desc: 'A stately Georgian manor in aged brick with symmetrical wings, a columned portico and boxwood parterres. Formal rooms, a clubby library and staff quarters over the garage.', features: ['Columned portico', 'Boxwood gardens', 'Formal dining room', 'Clubby library', 'Staff apartment', 'Circular drive'] },
  { id: 'g-georgian-2', cover: 'gen-georgian-2', status: 'sale', price: 3265000, beds: 6, baths: 5, sqft: 6630, year: 1955, building: 'Foxhall House', address: '1051 Foxhall Ln', city: 'McLean, VA', type: 'Georgian Manor', agent: 'Marcus Reed', desc: 'A stately Georgian manor in aged brick with symmetrical wings, a columned portico and boxwood parterres. Formal rooms, a clubby library and staff quarters over the garage.', features: ['Columned portico', 'Boxwood gardens', 'Formal dining room', 'Clubby library', 'Staff apartment', 'Circular drive'] },
  { id: 'g-georgian-3', cover: 'gen-georgian-3', status: 'sale', price: 4335000, beds: 7, baths: 6, sqft: 8070, year: 1981, building: 'Sheridan Hall', address: '1262 Sheridan Ct', city: 'Winnetka, IL', type: 'Georgian Manor', agent: 'Priya Anand', desc: 'A stately Georgian manor in aged brick with symmetrical wings, a columned portico and boxwood parterres. Formal rooms, a clubby library and staff quarters over the garage.', features: ['Columned portico', 'Boxwood gardens', 'Formal dining room', 'Clubby library', 'Staff apartment', 'Circular drive'] },
  { id: 'g-georgian-4', cover: 'gen-georgian-4', status: 'sale', price: 5400000, beds: 8, baths: 6, sqft: 9500, year: 2008, building: 'Governor\'s House', address: '1473 Governor\'s Way', city: 'Chestnut Hill, MA', type: 'Georgian Manor', agent: 'Elena Cruz', desc: 'A stately Georgian manor in aged brick with symmetrical wings, a columned portico and boxwood parterres. Formal rooms, a clubby library and staff quarters over the garage.', features: ['Columned portico', 'Boxwood gardens', 'Formal dining room', 'Clubby library', 'Staff apartment', 'Circular drive'] },
  { id: 'g-dutchcol-1', cover: 'gen-dutchcol-1', status: 'sale', price: 720000, beds: 3, baths: 2, sqft: 2000, year: 1918, building: 'The Gambrel', address: '877 Gambrel Way', city: 'Montclair, NJ', type: 'Dutch Colonial', agent: 'Elena Cruz', desc: 'A classic Dutch colonial with its signature gambrel roof, flared eaves and sun-splashed breakfast porch. Period charm with a renovated kitchen and finished third floor.', features: ['Gambrel roofline', 'Sunroom porch', 'Renovated kitchen', 'Finished third floor', 'Original hardwoods', 'Corner lot'] },
  { id: 'g-dutchcol-2', cover: 'gen-dutchcol-2', status: 'rent', price: 4450, beds: 4, baths: 3, sqft: 2470, year: 1925, building: 'Windmill House', address: '1088 Windmill Ln', city: 'Larchmont, NY', type: 'Dutch Colonial Rental', agent: 'Dana Whitmore', desc: 'A classic Dutch colonial with its signature gambrel roof, flared eaves and sun-splashed breakfast porch. Period charm with a renovated kitchen and finished third floor.', features: ['Gambrel roofline', 'Sunroom porch', 'Renovated kitchen', 'Finished third floor', 'Original hardwoods', 'Corner lot'] },
  { id: 'g-dutchcol-3', cover: 'gen-dutchcol-3', status: 'sale', price: 1240000, beds: 4, baths: 3, sqft: 2930, year: 1931, building: 'Van Ness Colonial', address: '1299 Van Ness Pl', city: 'West Hartford, CT', type: 'Dutch Colonial', agent: 'Marcus Reed', desc: 'A classic Dutch colonial with its signature gambrel roof, flared eaves and sun-splashed breakfast porch. Period charm with a renovated kitchen and finished third floor.', features: ['Gambrel roofline', 'Sunroom porch', 'Renovated kitchen', 'Finished third floor', 'Original hardwoods', 'Corner lot'] },
  { id: 'g-dutchcol-4', cover: 'gen-dutchcol-4', status: 'sale', price: 1500000, beds: 5, baths: 4, sqft: 3400, year: 1938, building: 'Orchard Hill', address: '1510 Orchard Hill Rd', city: 'Arlington, MA', type: 'Dutch Colonial', agent: 'Priya Anand', desc: 'A classic Dutch colonial with its signature gambrel roof, flared eaves and sun-splashed breakfast porch. Period charm with a renovated kitchen and finished third floor.', features: ['Gambrel roofline', 'Sunroom porch', 'Renovated kitchen', 'Finished third floor', 'Original hardwoods', 'Corner lot'] },
  { id: 'g-prairie-1', cover: 'gen-prairie-1', status: 'sale', price: 680000, beds: 3, baths: 2, sqft: 2400, year: 1910, building: 'Wrightwood House', address: '914 Wrightwood Ave', city: 'Oak Park, IL', type: 'Prairie Style', agent: 'Priya Anand', desc: 'A Prairie-style landmark with strong horizontal lines, art-glass windows and deep cantilevered eaves. Warm quarter-sawn oak and light-banded rooms that hug the landscape.', features: ['Art-glass windows', 'Cantilevered eaves', 'Quarter-sawn oak', 'Original fireplace inglenook', 'Architect pedigree', 'Corner gardens'] },
  { id: 'g-prairie-2', cover: 'gen-prairie-2', status: 'sale', price: 985000, beds: 4, baths: 3, sqft: 3000, year: 1918, building: 'Prairie Crossing', address: '1125 Prairie Crossing', city: 'Madison, WI', type: 'Prairie Style', agent: 'Elena Cruz', desc: 'A Prairie-style landmark with strong horizontal lines, art-glass windows and deep cantilevered eaves. Warm quarter-sawn oak and light-banded rooms that hug the landscape.', features: ['Art-glass windows', 'Cantilevered eaves', 'Quarter-sawn oak', 'Original fireplace inglenook', 'Architect pedigree', 'Corner gardens'] },
  { id: 'g-prairie-3', cover: 'gen-prairie-3', status: 'rent', price: 4950, beds: 4, baths: 3, sqft: 3600, year: 1927, building: 'Horizon House', address: '1336 Horizon Ln', city: 'Ann Arbor, MI', type: 'Prairie Style Rental', agent: 'Dana Whitmore', desc: 'A Prairie-style landmark with strong horizontal lines, art-glass windows and deep cantilevered eaves. Warm quarter-sawn oak and light-banded rooms that hug the landscape.', features: ['Art-glass windows', 'Cantilevered eaves', 'Quarter-sawn oak', 'Original fireplace inglenook', 'Architect pedigree', 'Corner gardens'] },
  { id: 'g-prairie-4', cover: 'gen-prairie-4', status: 'sale', price: 1600000, beds: 5, baths: 4, sqft: 4200, year: 1935, building: 'Ledgestone', address: '1547 Ledgestone Dr', city: 'Des Moines, IA', type: 'Prairie Style', agent: 'Marcus Reed', desc: 'A Prairie-style landmark with strong horizontal lines, art-glass windows and deep cantilevered eaves. Warm quarter-sawn oak and light-banded rooms that hug the landscape.', features: ['Art-glass windows', 'Cantilevered eaves', 'Quarter-sawn oak', 'Original fireplace inglenook', 'Architect pedigree', 'Corner gardens'] },
  { id: 'g-artdeco-1', cover: 'gen-artdeco-1', status: 'rent', price: 5200, beds: 3, baths: 2, sqft: 2200, year: 1936, building: 'Flamingo House', address: '951 Flamingo Ter', city: 'Miami Beach, FL', type: 'Art Deco Rental', agent: 'Marcus Reed', desc: 'A streamline moderne jewel with curved white walls, glass block and porthole accents, restored to the studs. A tiled pool patio channels pure 1930s glamour.', features: ['Curved glass block', 'Porthole windows', 'Restored terrazzo', 'Tiled pool patio', 'Historic pedigree', 'Roof deck'] },
  { id: 'g-artdeco-2', cover: 'gen-artdeco-2', status: 'sale', price: 1700000, beds: 4, baths: 3, sqft: 2870, year: 1940, building: 'Streamline Moderne', address: '1162 Streamline Dr', city: 'Los Angeles, CA', type: 'Art Deco', agent: 'Priya Anand', desc: 'A streamline moderne jewel with curved white walls, glass block and porthole accents, restored to the studs. A tiled pool patio channels pure 1930s glamour.', features: ['Curved glass block', 'Porthole windows', 'Restored terrazzo', 'Tiled pool patio', 'Historic pedigree', 'Roof deck'] },
  { id: 'g-artdeco-3', cover: 'gen-artdeco-3', status: 'sale', price: 2250000, beds: 4, baths: 3, sqft: 3530, year: 1944, building: 'Deco Villa', address: '1373 Deco Ct', city: 'Tulsa, OK', type: 'Art Deco', agent: 'Elena Cruz', desc: 'A streamline moderne jewel with curved white walls, glass block and porthole accents, restored to the studs. A tiled pool patio channels pure 1930s glamour.', features: ['Curved glass block', 'Porthole windows', 'Restored terrazzo', 'Tiled pool patio', 'Historic pedigree', 'Roof deck'] },
  { id: 'g-artdeco-4', cover: 'gen-artdeco-4', status: 'rent', price: 9800, beds: 5, baths: 4, sqft: 4200, year: 1948, building: 'Ocean Park Deco', address: '1584 Ocean Park Ave', city: 'Fort Lauderdale, FL', type: 'Art Deco Rental', agent: 'Dana Whitmore', desc: 'A streamline moderne jewel with curved white walls, glass block and porthole accents, restored to the studs. A tiled pool patio channels pure 1930s glamour.', features: ['Curved glass block', 'Porthole windows', 'Restored terrazzo', 'Tiled pool patio', 'Historic pedigree', 'Roof deck'] },
  { id: 'g-cotswold-1', cover: 'gen-cotswold-1', status: 'sale', price: 850000, beds: 2, baths: 2, sqft: 1400, year: 1922, building: 'Ivy Cottage', address: '988 Fairy Tale Ln', city: 'Carmel, CA', type: 'Stone Cottage', agent: 'Dana Whitmore', desc: 'A storybook stone cottage wrapped in ivy, with a swooping cedar roof, arched plank door and leaded casements. An English garden and studio complete the fairy tale.', features: ['Hand-laid stone', 'Arched plank door', 'Leaded casements', 'English garden', 'Detached studio', 'Village location'] },
  { id: 'g-cotswold-2', cover: 'gen-cotswold-2', status: 'rent', price: 5300, beds: 3, baths: 2, sqft: 2000, year: 1934, building: 'Stonepath', address: '1199 Stonepath Way', city: 'Woodstock, NY', type: 'Stone Cottage Rental', agent: 'Marcus Reed', desc: 'A storybook stone cottage wrapped in ivy, with a swooping cedar roof, arched plank door and leaded casements. An English garden and studio complete the fairy tale.', features: ['Hand-laid stone', 'Arched plank door', 'Leaded casements', 'English garden', 'Detached studio', 'Village location'] },
  { id: 'g-cotswold-3', cover: 'gen-cotswold-3', status: 'sale', price: 1900000, beds: 4, baths: 3, sqft: 2600, year: 1945, building: 'Hollow Cottage', address: '1410 Hobbit Hollow', city: 'Lake Geneva, WI', type: 'Stone Cottage', agent: 'Priya Anand', desc: 'A storybook stone cottage wrapped in ivy, with a swooping cedar roof, arched plank door and leaded casements. An English garden and studio complete the fairy tale.', features: ['Hand-laid stone', 'Arched plank door', 'Leaded casements', 'English garden', 'Detached studio', 'Village location'] },
  { id: 'x-house-modern', cover: 'house-modern', status: 'sale', price: 1450000, beds: 5, baths: 4, sqft: 3600, year: 2024, building: 'The Cedarview', address: '200 Lakeshore Dr', city: 'Bellevue, WA', type: 'Single Family Home', agent: 'Dana Whitmore', desc: 'A striking contemporary home with floor-to-ceiling glass, warm oak accents and a chef\'s kitchen on a landscaped lot minutes from downtown.', features: ['Chef\'s kitchen with quartz island', 'Floor-to-ceiling windows', 'Primary suite with spa bath', 'Smart-home wiring', 'Two-car garage', 'Fenced backyard'] },
  { id: 'x-house-suburban', cover: 'house-suburban', status: 'sale', price: 720000, beds: 4, baths: 3, sqft: 2600, year: 2016, building: 'Maple Grove', address: '343 Birchwood Ln', city: 'Naperville, IL', type: 'Single Family Home', agent: 'Marcus Reed', desc: 'Classic suburban charm on a quiet tree-lined street with a bright eat-in kitchen, finished basement and a generous fenced yard.', features: ['Finished basement', 'Eat-in kitchen', 'Attached garage', 'Fenced yard', 'New HVAC', 'Walk to schools'] },
  { id: 'x-condo-tower', cover: 'condo-tower', status: 'sale', price: 1290000, beds: 3, baths: 2, sqft: 1600, year: 2023, building: 'One Harbor Residences', address: '486 Marina Blvd', city: 'Boston, MA', type: 'High-Rise Condo', agent: 'Priya Anand', desc: 'A sun-drenched high-rise residence with sweeping views, a designer kitchen and full building amenities including a gym and roof deck.', features: ['Skyline views', '24-hour concierge', 'Fitness center & roof deck', 'In-unit laundry', 'Deeded parking', 'Pet friendly'] },
  { id: 'x-townhouse', cover: 'townhouse', status: 'sale', price: 760000, beds: 3, baths: 2, sqft: 2100, year: 2022, building: 'Elmstone Place', address: '629 Elmstone Row', city: 'Denver, CO', type: 'Townhouse', agent: 'Elena Cruz', desc: 'A modern townhome with flexible multi-level living, a private terrace and an attached garage, steps from cafes and transit.', features: ['Private rooftop terrace', 'Attached garage', 'Hardwood throughout', 'Energy-efficient windows', 'Low HOA', 'Near light rail'] },
  { id: 'x-villa', cover: 'villa', status: 'sale', price: 3400000, beds: 6, baths: 5, sqft: 4800, year: 2024, building: 'Casa Palma', address: '772 Sunset Ridge', city: 'Scottsdale, AZ', type: 'Luxury Villa', agent: 'Dana Whitmore', desc: 'An architectural villa with a resort-style pool, disappearing glass walls and a gourmet outdoor kitchen for year-round entertaining.', features: ['Resort-style pool & spa', 'Disappearing glass walls', 'Outdoor kitchen', 'Home theater', '3-car garage', 'Smart climate control'] },
  { id: 'x-apartment', cover: 'apartment', status: 'rent', price: 3200, beds: 2, baths: 2, sqft: 1200, year: 2022, building: 'Parkview Tower', address: '915 Parkview Ave', city: 'Seattle, WA', type: 'Apartment Rental', agent: 'Marcus Reed', desc: 'A bright apartment with a private balcony, modern finishes, in-unit laundry and access to a resident lounge and courtyard.', features: ['Private balcony', 'In-unit washer/dryer', 'Resident gym & lounge', 'Stainless appliances', 'Garage parking', 'Pet friendly'] },
  { id: 'x-house-mansion', cover: 'house-mansion', status: 'sale', price: 6200000, beds: 7, baths: 6, sqft: 8400, year: 2024, building: 'The Overlook Estate', address: '1058 Summit Ridge', city: 'Beverly Hills, CA', type: 'Luxury Estate', agent: 'Priya Anand', desc: 'A show-stopping modern estate wrapped in glass and concrete, with grand entertaining spaces flowing to private garden terraces.', features: ['Grand two-story foyer', 'Chef\'s catering kitchen', 'Home theater & wine cellar', 'Resort pool & spa', '4-car garage', 'Smart-home automation'] },
  { id: 'x-house-cabin', cover: 'house-cabin', status: 'sale', price: 585000, beds: 3, baths: 2, sqft: 1650, year: 2016, building: 'Pinecrest Lodge', address: '1201 Timberline Trail', city: 'Big Bear Lake, CA', type: 'Cabin', agent: 'Elena Cruz', desc: 'A warm timber cabin tucked into the pines with vaulted wood ceilings, a stone fireplace and a wraparound deck under the trees.', features: ['Stone wood-burning fireplace', 'Vaulted timber ceilings', 'Wraparound deck', 'Hot tub', 'Detached workshop', 'Forested private lot'] },
  { id: 'x-house-colonial', cover: 'house-colonial', status: 'sale', price: 725000, beds: 5, baths: 4, sqft: 3100, year: 2004, building: 'Heritage Row', address: '1344 Chestnut St', city: 'Princeton, NJ', type: 'Colonial', agent: 'Dana Whitmore', desc: 'A classic red-brick colonial with white trim, hardwood floors and generous, light-filled rooms on a deep, well-landscaped lot.', features: ['Hardwood floors throughout', 'Formal dining room', 'Updated eat-in kitchen', 'Finished basement', 'Two-car garage', 'Mature landscaping'] },
  { id: 'x-house-beach', cover: 'house-beach', status: 'sale', price: 2650000, beds: 5, baths: 4, sqft: 3800, year: 2023, building: 'Dune Crest', address: '1487 Shoreline Way', city: 'Malibu, CA', type: 'Beach House', agent: 'Marcus Reed', desc: 'A breezy coastal retreat on stilts with panoramic ocean views, an open great room and expansive decks steps from the sand.', features: ['Panoramic ocean views', 'Wraparound decks', 'Open great room', 'Outdoor shower', 'Elevated hurricane-rated build', 'Steps to the beach'] },
  { id: 'x-house-penthouse', cover: 'house-penthouse', status: 'sale', price: 5400000, beds: 4, baths: 3, sqft: 4200, year: 2023, building: 'The Aster', address: '1630 Skyline Ave', city: 'New York, NY', type: 'Penthouse', agent: 'Priya Anand', desc: 'A full-floor penthouse crowning the tower with wraparound terraces, floor-to-ceiling glass and skyline views in every direction.', features: ['Wraparound private terraces', 'Floor-to-ceiling glass', 'Chef\'s kitchen', 'Concierge & valet', 'Two deeded parking spaces', 'Skyline views'] },
  { id: 'x-house-farmhouse', cover: 'house-farmhouse', status: 'sale', price: 895000, beds: 4, baths: 3, sqft: 3200, year: 2020, building: 'Oakhaven Farm', address: '1773 County Line Rd', city: 'Franklin, TN', type: 'Modern Farmhouse', agent: 'Elena Cruz', desc: 'A charming modern farmhouse with a wraparound porch, shiplap accents and a big country kitchen shaded by a grand old oak.', features: ['Wraparound porch', 'Country chef\'s kitchen', 'Shiplap accents', 'Barn-style garage', 'Fenced acreage', 'Wood-burning stove'] },
];
