import type { Contact, ChatMessage } from '../../state/useMessagesStore';

// ─────────────────────────────────────────────────────────────────────────────
// Contextual reply engine
//
// There is no runtime LLM in this simulation, so replies are generated by a
// rich, deterministic intent-matcher. We classify the user's message into an
// intent, then pick a persona-appropriate response for the contact's
// relationship (manager, recruiter, colleague, LinkedIn connection, mentor, HR,
// client). Responses interpolate the user's name, the contact, their company
// and role so the conversation feels tailored rather than canned.
// ─────────────────────────────────────────────────────────────────────────────

export type Intent =
  | 'greeting'
  | 'thanks'
  | 'pto'
  | 'raise'
  | 'deadline'
  | 'meeting'
  | 'blocker'
  | 'feedback'
  | 'opportunity'
  | 'networking'
  | 'availability'
  | 'status'
  | 'congrats'
  | 'apology'
  | 'smalltalk';

const has = (t: string, ...words: string[]) => words.some((w) => t.includes(w));

export function classify(raw: string): Intent {
  const t = raw.toLowerCase();
  if (has(t, 'thank', 'thanks', 'appreciate', 'grateful')) return 'thanks';
  if (has(t, 'sorry', 'apolog', 'my bad', 'my fault')) return 'apology';
  if (has(t, 'congrat', 'well done', 'nice work', 'proud of you')) return 'congrats';
  if (has(t, 'raise', 'promotion', 'promoted', 'compensation', 'salary', 'more money', 'pay bump')) return 'raise';
  if (has(t, 'pto', 'time off', 'vacation', 'day off', 'sick', 'out of office', 'ooo', 'leave')) return 'pto';
  if (has(t, 'deadline', 'due date', 'ship', 'launch', 'when is', 'by when', 'timeline')) return 'deadline';
  if (has(t, 'blocked', 'blocker', 'stuck', 'help me', 'can you help', 'issue', 'bug', 'broken', 'not working')) return 'blocker';
  if (has(t, 'meet', 'call', 'sync', 'catch up', 'grab coffee', 'chat', '1:1', 'one on one', 'zoom', 'schedule')) return 'meeting';
  if (has(t, 'feedback', 'review', 'how am i doing', 'thoughts on', 'what do you think')) return 'feedback';
  if (has(t, 'role', 'position', 'opening', 'opportunity', 'hiring', 'job', 'interview', 'apply', 'referral', 'refer me')) return 'opportunity';
  if (has(t, 'connect', 'network', 'introduce', 'intro to', 'advice', 'mentor', 'guidance', 'coffee chat')) return 'networking';
  if (has(t, 'free', 'available', 'availability', 'what time', 'when are you', 'tomorrow', 'later today')) return 'availability';
  if (has(t, 'status', 'update', 'progress', 'where are we', 'how is', 'how are things')) return 'status';
  if (has(t, 'hi', 'hey', 'hello', 'good morning', 'good afternoon', 'yo ')) return 'greeting';
  if (t.trim().length <= 3 || has(t, 'ok', 'okay', 'cool', 'got it', 'sounds good', 'sure')) return 'smalltalk';
  return 'status';
}

type Ctx = { contact: Contact; first: string };
type Bank = Partial<Record<Intent, (c: Ctx) => string[]>>;

// Fallbacks used when a persona has no specific line for the intent.
const GENERIC: Record<Intent, (c: Ctx) => string[]> = {
  greeting: ({ first }) => [`Hey ${first}! Good to hear from you. What's up?`, `Hi ${first} — how's it going?`],
  thanks: () => [`Of course — anytime.`, `Happy to help. That's what I'm here for.`],
  apology: () => [`No worries at all, honestly. These things happen.`, `Don't sweat it — we're good.`],
  congrats: () => [`Thank you! That means a lot coming from you.`, `Appreciate it.`],
  raise: ({ first }) => [`That's a fair thing to raise, ${first}. Let's find time to talk it through properly.`],
  pto: () => [`Sounds good — go recharge. We'll hold things down.`, `Enjoy the time off, you've earned it.`],
  deadline: () => [`Let me check the timeline and get back to you with a firm date.`],
  blocker: ({ first }) => [`Okay ${first}, walk me through it — what have you tried so far?`, `Let's unblock this. Can you share where exactly it's failing?`],
  meeting: () => [`Works for me. Send an invite and I'll accept.`, `Let's do it — I'll find a slot that works for both of us.`],
  feedback: ({ first }) => [`Honestly ${first}, you're doing solid work. A couple of small things we can polish, but you're on track.`],
  opportunity: () => [`Interesting — tell me a bit more about what you're looking for.`],
  networking: () => [`Happy to connect. Always glad to make time for people doing good work.`],
  availability: () => [`I've got some open time this afternoon and tomorrow morning. What suits you?`],
  status: ({ first }) => [`Things are moving along, ${first}. Anything specific you wanted an update on?`],
  smalltalk: () => [`Sounds good.`, `For sure.`],
};

const BANKS: Record<Contact['relationship'], Bank> = {
  manager: {
    greeting: ({ first }) => [`Morning ${first}. Good timing — I was about to ping you. How are you feeling about this sprint?`],
    pto: ({ first }) => [
      `Absolutely, ${first} — take the time. Just drop the dates in the team calendar and make sure your work-in-progress is handed off. You don't need to check in while you're out.`,
      `Approved. You've been putting in real hours, so go recharge. I'll cover anything urgent that comes up.`,
    ],
    raise: ({ first, contact }) => [
      `I'm glad you brought it up, ${first}. Your impact this cycle has been clear — the ${contact.company} leadership review is next month, and I'd like to put you forward. Can you pull together a short summary of your wins so I can make the strongest case?`,
      `Let's talk numbers properly. Send me three or four concrete outcomes you've driven and I'll take it into the comp calibration.`,
    ],
    deadline: () => [
      `The launch is locked for the end of the month, but I'd rather ship it right than ship it fast. If you need another few days on the risky parts, tell me now and I'll manage upward.`,
    ],
    blocker: ({ first }) => [
      `Thanks for flagging it early, ${first} — that's exactly what I want. Who else is affected? If it's a dependency I can go knock on the other team's door and clear it for you today.`,
    ],
    feedback: ({ first }) => [
      `Straight answer, ${first}: you're one of the more reliable people on the team. Where I'd push you is to speak up sooner in reviews — your instincts are good and people should hear them. Keep doing what you're doing on delivery.`,
    ],
    meeting: () => [`Let's grab our 1:1 slot — Thursday 2pm still work? I'll keep it loose so we can cover whatever's on your mind.`],
    status: ({ first }) => [`Give me the headline, ${first} — green, yellow, or red? If it's yellow or red I'd rather know what you need than hear it's fine.`],
    availability: () => [`I'm in back-to-backs till noon, then free. Grab whatever works after that.`],
  },
  recruiter: {
    greeting: ({ first, contact }) => [`Hi ${first}! Thanks for getting back to me. I think the ${contact.company} team could be a great fit for your background — do you have 15 minutes this week for a quick call?`],
    opportunity: ({ first, contact }) => [
      `Great to hear you're open, ${first}. The role is a Senior position on the ${contact.company} team — strong comp, hybrid, and a manager who's genuinely invested in growth. Want me to send the full JD and set up an intro call?`,
      `Perfect timing. We just opened a req that lines up with your experience. I can fast-track you past the initial screen — are you interviewing elsewhere right now so I can pace this appropriately?`,
    ],
    availability: () => [`I have slots Tuesday at 11am or Wednesday at 3pm ET. Which works? I'll send a calendar hold and the video link.`],
    raise: () => [`Comp for this band typically lands well above market, and there's room to negotiate on sign-on. Let's get you through the loop and I'll advocate hard on the number.`],
    meeting: ({ first }) => [`Let's set it up, ${first}. I'll send an invite with a Google Meet link — come with any questions about the team, the interview process, or comp.`],
    networking: ({ contact }) => [`Even if the timing isn't right, I'm happy to keep you in mind for future ${contact.company} roles. I'll add you to my network and reach out when something sharper comes up.`],
    status: ({ first }) => [`Quick update, ${first}: the hiring manager loved your profile. Next step is a 45-minute technical conversation. Shall I lock it in?`],
  },
  colleague: {
    greeting: ({ first }) => [`yo ${first}! what's good`, `hey! perfect timing, i was just about to message you`],
    blocker: () => [`ohh yeah i hit that same thing last week. it's the config — check the env vars, that fixed it for me. lmk if it's still broken and i'll hop on a call`],
    meeting: () => [`down to sync. i'm free after standup, wanna just grab a room? or coffee if you'd rather get out of the building`],
    deadline: () => [`i think we're okay on timing but the review step always takes longer than people expect. wanna pair on it tomorrow so we're not scrambling friday?`],
    smalltalk: () => [`haha yeah`, `fr`, `100%`],
    status: ({ first }) => [`going alright ${first}, just buried in reviews. you? need anything from me?`],
    thanks: () => [`anytime dude`],
    availability: () => [`free most of the afternoon, ping me whenever`],
  },
  linkedin: {
    greeting: ({ first, contact }) => [`Hi ${first}, thanks for reaching out and for connecting! Always happy to meet someone else in the ${contact.company} orbit.`],
    networking: ({ first }) => [
      `Absolutely, ${first} — I'm always glad to pay it forward. Happy to do a 20-minute call and share what I've learned. What specifically are you hoping to get out of it, so I can make it useful?`,
      `Of course. The best advice I can give is to be specific about what you want — a warm intro, portfolio feedback, or a read on the market. Tell me which and I'll do my best.`,
    ],
    opportunity: ({ contact }) => [`We are hiring, actually. I can't guarantee anything, but if you send me your resume I'm glad to refer you internally at ${contact.company} — referrals get a real look here.`],
    feedback: () => [`Happy to take a look. Send it over and I'll give you honest, specific notes — that's more useful than politeness.`],
    meeting: ({ first }) => [`Let's do a coffee chat, ${first}. I'll send over a couple of times — virtual is easiest for me but I'm flexible.`],
    thanks: () => [`My pleasure — reach out anytime. That's what the network is for.`],
    status: () => [`Things are busy but good on my end. What's prompting the outreach — anything I can help with?`],
  },
  mentor: {
    greeting: ({ first }) => [`Good to hear from you, ${first}. I always have time for you — what's on your mind?`],
    feedback: ({ first }) => [
      `Here's my honest read, ${first}: you're more capable than you give yourself credit for. The gap isn't skill, it's visibility — make sure the right people see your work. Pick one project this quarter and over-communicate the impact.`,
    ],
    raise: ({ first }) => [`Before you ask for the raise, ${first}, build the case: quantify what you've delivered and what it saved or earned. Walk in with evidence, not hope. Managers want to say yes — make it easy for them.`],
    blocker: () => [`Step back for a second. What would you tell a friend who was stuck on this? Usually the answer's already in you. Then tell me and I'll pressure-test it.`],
    networking: ({ first }) => [`Proud of you for reaching out, ${first}. The people who ask for help early move fastest. Let's set a standing monthly call so this isn't a one-off.`],
    status: ({ first }) => [`Tell me the real version, ${first}, not the polished one. Where are you actually struggling?`],
    congrats: ({ first }) => [`I knew you'd get there, ${first}. Enjoy it — then let's talk about the next mountain.`],
  },
  hr: {
    greeting: ({ first }) => [`Hello ${first}, thanks for reaching out to People Operations. How can I help you today?`],
    pto: ({ first }) => [`Of course, ${first}. You currently have 14 days of PTO remaining. Submit the request in Workday and it'll route to your manager automatically — you'll get a confirmation email once it's approved.`],
    raise: () => [`Compensation reviews happen during the mid-year cycle, but off-cycle adjustments are possible with manager sponsorship. I'd recommend starting that conversation with your manager, and I'm happy to explain the process in detail.`],
    status: ({ first }) => [`Everything looks in good standing on your record, ${first}. Is there a specific benefit, policy, or document you needed?`],
    thanks: () => [`You're very welcome. Don't hesitate to reach out — that's what we're here for.`],
    meeting: () => [`I can set up a confidential 30-minute call. Would sometime this week work? Everything we discuss stays between us.`],
  },
  client: {
    greeting: ({ first }) => [`Hi ${first}, good to connect. We've been looking forward to getting this project moving.`],
    deadline: () => [`Understood. Our board is expecting the first milestone by month-end — is that still realistic on your side? We'd rather adjust scope than quality if it's tight.`],
    status: ({ first }) => [`Thanks for the check-in, ${first}. On our end we're ready for the next phase whenever you are. What do you need from us to keep momentum?`],
    meeting: () => [`Let's schedule a review. I'll loop in our stakeholders — can you send a few times that work next week?`],
    thanks: () => [`The pleasure's ours. It's been a genuinely smooth engagement so far.`],
  },
};

/**
 * Generate a contextual reply. `turnSeed` (e.g. the message count) is used to
 * rotate through response variants so repeated intents don't repeat verbatim.
 */
export function generateReply(contact: Contact, userText: string, history: ChatMessage[], firstName = 'there'): string {
  const intent = classify(userText);
  const first = firstName;
  const ctx: Ctx = { contact, first };
  const bank = BANKS[contact.relationship] ?? {};
  const options = (bank[intent]?.(ctx) ?? GENERIC[intent](ctx)).filter((s) => s.trim().length > 0);
  const pool = options.length > 0 ? options : GENERIC.status(ctx);
  const turnSeed = history.filter((m) => m.from === 'me').length;
  return pool[turnSeed % pool.length];
}

/** A realistic typing delay proportional to the reply length. */
export function replyDelay(text: string): number {
  return Math.min(2600, 650 + text.length * 12);
}
